# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ups_test.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'ups_test.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eups_test.proto\x12\x04Test*D\n\nTestResult\x12\x0f\n\x0bTEST_FAILED\x10\x00\x12\x10\n\x0cTEST_PENDING\x10\x01\x12\x13\n\x0fTEST_SUCCESSFUL\x10\x02*\x9f\x03\n\x08TestType\x12 \n\x1cLIGHT_LOAD_AND_FUNCTION_TEST\x10\x00\x12\x10\n\x0cNO_LOAD_TEST\x10\x01\x12\x12\n\x0e\x46ULL_LOAD_TEST\x10\x02\x12\x14\n\x10\x41\x43_INPUT_FAILURE\x10\x03\x12\x13\n\x0f\x41\x43_INPUT_RETURN\x10\x04\x12\x16\n\x12INPUT_POWER_FACTOR\x10\x05\x12\x19\n\x15\x43HANGE_OPERATION_MODE\x10\x06\x12\x16\n\x12STORED_ENERGY_TIME\x10\x07\x12\x0e\n\nSwitchTest\x10\x08\x12\x0e\n\nBackupTest\x10\t\x12\x12\n\x0e\x45\x66\x66iciencyTest\x10\n\x12!\n\x1dSteadyState_InputVoltage_Test\x10\x0b\x12\x10\n\x0cWaveformTest\x10\x0c\x12\x1a\n\x16\x45\x46\x46ICIENCY_NORMAL_MODE\x10\x0e\x12\x1b\n\x17\x45\x46\x46ICIENCY_STORAGE_MODE\x10\x0f\x12\x18\n\x14OVERLOAD_NORMAL_MODE\x10\x10\x12\x19\n\x15OVERLOAD_STORAGE_MODE\x10\x11\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ups_test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TESTRESULT']._serialized_start=24
  _globals['_TESTRESULT']._serialized_end=92
  _globals['_TESTTYPE']._serialized_start=95
  _globals['_TESTTYPE']._serialized_end=510
# @@protoc_insertion_point(module_scope)
